//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServidorCheckers
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Jugador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jugador()
        {
            this.Partidas = new ObservableCollection<Partida>();
            this.Partidas1 = new ObservableCollection<Partida>();
            this.Rankings = new ObservableCollection<Ranking>();
            this.Reportes = new ObservableCollection<Reporte>();
            this.Reportes1 = new ObservableCollection<Reporte>();
            this.Reputacions = new ObservableCollection<Reputacion>();
        }
    
        public int idJugador { get; set; }
        public string apodo { get; set; }
        public string contrasenia { get; set; }
        public string correoElectronico { get; set; }
        public string status { get; set; }
        public string respuestaConfirmacion { get; set; }
        public string preguntaRecuperacion { get; set; }
        public string pinConfirmacion { get; set; }
        public int idCreador { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Partida> Partidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Partida> Partidas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Ranking> Rankings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Reporte> Reportes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Reporte> Reportes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Reputacion> Reputacions { get; set; }
    }
}
