//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServidorCheckers
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Partida
    {
        public int idPartida { get; set; }
        public Nullable<System.TimeSpan> tiempo { get; set; }
        public string modoJuego { get; set; }
        public Nullable<int> turno { get; set; }
        public int idGanador { get; set; }
        public int idPerdedor { get; set; }
    
        public virtual Jugador Jugador { get; set; }
        public virtual Jugador Jugador1 { get; set; }
    }
}
