//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServidorCheckers
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Ranking
    {
        public int idRanking { get; set; }
        public int idDuenio { get; set; }
        public Nullable<System.DateTime> fechaRegistracion { get; set; }
        public Nullable<int> numeroVictorias { get; set; }
        public Nullable<int> partidasJugadas { get; set; }
        public Nullable<int> rank { get; set; }
        public Nullable<int> numeroPerdidas { get; set; }
    
        public virtual Jugador Jugador { get; set; }
    }
}
