//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServidorCheckers
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Reporte
    {
        public int idReporte { get; set; }
        public int idAcusador { get; set; }
        public int idReportado { get; set; }
        public string descripcionAcuso { get; set; }
    
        public virtual Jugador Jugador { get; set; }
        public virtual Jugador Jugador1 { get; set; }
    }
}
