//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServidorCheckers
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Reputacion
    {
        public int idReputacion { get; set; }
        public int idDuenio { get; set; }
        public Nullable<int> numeroReportes { get; set; }
        public Nullable<int> numeroVecesReportado { get; set; }
    
        public virtual Jugador Jugador { get; set; }
    }
}
