//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckersCliente.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckersCliente.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Answer.
        /// </summary>
        public static string AnswerQuestion {
            get {
                return ResourceManager.GetString("AnswerQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change your password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation question.
        /// </summary>
        public static string ConfirmationQuestion {
            get {
                return ResourceManager.GetString("ConfirmationQuestion", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string E_mail {
            get {
                return ResourceManager.GetString("E-mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your e-mail.
        /// </summary>
        public static string EnterMail {
            get {
                return ResourceManager.GetString("EnterMail", resourceCulture);
                }
            }
        ///   Looks up a localized string similar to Games Lost.
        /// </summary>
        public static string GamesLost {
            get {
                return ResourceManager.GetString("GamesLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your nickname.
        /// </summary>
        public static string EnterNickname {
            get {
                return ResourceManager.GetString("EnterNickname", resourceCulture);
                }
            }
        ///   Looks up a localized string similar to Games Played.
        /// </summary>
        public static string GamesPlayed {
            get {
                return ResourceManager.GetString("GamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your Pin.
        /// </summary>
        public static string EnterPin {
            get {
                return ResourceManager.GetString("EnterPin", resourceCulture);
                }
            }
        ///   Looks up a localized string similar to Games Won.
        /// </summary>
        public static string GamesWon {
            get {
                return ResourceManager.GetString("GamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una o mas casillas no contienen los elementos minimos suficientes.
        /// </summary>
        public static string MinimunLength {
            get {
                return ResourceManager.GetString("MinimunLength", resourceCulture);
                }
            }
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nickname.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your nickname to receive a confirmation pin on your linked mail and change your password.
        /// </summary>
        public static string NicknameInstructions {
            get {
                return ResourceManager.GetString("NicknameInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register new account.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
                }
            }
        ///   Looks up a localized string similar to Rankings Table.
        /// </summary>
        public static string Rankings {
            get {
                return ResourceManager.GetString("Rankings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resend e-mail.
        /// </summary>
        public static string ResendE_mail {
            get {
                return ResourceManager.GetString("ResendE-mail", resourceCulture);
                }
            }
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rules.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send mail.
        /// </summary>
        public static string SendMail {
            get {
                return ResourceManager.GetString("SendMail", resourceCulture);
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify account.
        /// </summary>
        public static string VerifyAccount {
            get {
                return ResourceManager.GetString("VerifyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        public static string VerifyPassword {
            get {
                return ResourceManager.GetString("VerifyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please wait till the timer ends to resend the mail.
        /// </summary>
        public static string WaitMessage {
            get {
                return ResourceManager.GetString("WaitMessage", resourceCulture);
            }
        }
    }
}
