//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        public int idPartida { get; set; }
        public Nullable<System.TimeSpan> tiempo { get; set; }
        public string modoJuego { get; set; }
        public Nullable<int> turno { get; set; }
        public int idGanador { get; set; }
        public int idPerdedor { get; set; }
    
        public virtual Jugador Jugador { get; set; }
        public virtual Jugador Jugador1 { get; set; }
    }
}
