//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ranking
    {
        public int idRanking { get; set; }
        public int idDuenio { get; set; }
        public Nullable<System.DateTime> fechaRegistracion { get; set; }
        public Nullable<int> numeroVictorias { get; set; }
        public Nullable<int> partidasJugadas { get; set; }
        public Nullable<int> rank { get; set; }
        public Nullable<int> numeroPerdidas { get; set; }
    
        public virtual Jugador Jugador { get; set; }
    }
}
