//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public int idReporte { get; set; }
        public int idAcusador { get; set; }
        public int idReportado { get; set; }
        public string descripcionAcuso { get; set; }
        public virtual Jugador Jugador { get; set; }
        public virtual Jugador Jugador1 { get; set; }
    }
}
