//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckersCliente.MainService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
    [System.SerializableAttribute()]
    public partial class Jugador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCreadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdLenguajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinConfirmacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreguntaRecuperacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RespuestaConfirmacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apodo {
            get {
                return this.ApodoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApodoField, value) != true)) {
                    this.ApodoField = value;
                    this.RaisePropertyChanged("Apodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCreador {
            get {
                return this.IdCreadorField;
            }
            set {
                if ((this.IdCreadorField.Equals(value) != true)) {
                    this.IdCreadorField = value;
                    this.RaisePropertyChanged("IdCreador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJugador {
            get {
                return this.IdJugadorField;
            }
            set {
                if ((this.IdJugadorField.Equals(value) != true)) {
                    this.IdJugadorField = value;
                    this.RaisePropertyChanged("IdJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLenguaje {
            get {
                return this.IdLenguajeField;
            }
            set {
                if ((this.IdLenguajeField.Equals(value) != true)) {
                    this.IdLenguajeField = value;
                    this.RaisePropertyChanged("IdLenguaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PinConfirmacion {
            get {
                return this.PinConfirmacionField;
            }
            set {
                if ((object.ReferenceEquals(this.PinConfirmacionField, value) != true)) {
                    this.PinConfirmacionField = value;
                    this.RaisePropertyChanged("PinConfirmacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreguntaRecuperacion {
            get {
                return this.PreguntaRecuperacionField;
            }
            set {
                if ((object.ReferenceEquals(this.PreguntaRecuperacionField, value) != true)) {
                    this.PreguntaRecuperacionField = value;
                    this.RaisePropertyChanged("PreguntaRecuperacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RespuestaConfirmacion {
            get {
                return this.RespuestaConfirmacionField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaConfirmacionField, value) != true)) {
                    this.RespuestaConfirmacionField = value;
                    this.RaisePropertyChanged("RespuestaConfirmacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResult", Namespace="http://schemas.datacontract.org/2004/07/Contratos")]
    public enum LoginResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordIncorrecto = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoExisteJugador = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExisteJugadorVerificado = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExisteJugadorNoVerificado = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveResult", Namespace="http://schemas.datacontract.org/2004/07/Contratos")]
    public enum SaveResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JugadorGuardado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NicknameExistente = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CorreoExistente = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorGuardado = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerificationResult", Namespace="http://schemas.datacontract.org/2004/07/Contratos")]
    public enum VerificationResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PinIncorrecto = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoExisteJugador = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificacionExistosa = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailResult", Namespace="http://schemas.datacontract.org/2004/07/Contratos")]
    public enum MailResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MailSend = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SendError = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownPlayer = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PinResult", Namespace="http://schemas.datacontract.org/2004/07/Contratos")]
    public enum PinResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerifiedPin = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownPin = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MainService.IPlayerManager", CallbackContract=typeof(CheckersCliente.MainService.IPlayerManagerCallback))]
    public interface IPlayerManager {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/Login")]
        void Login(CheckersCliente.MainService.Jugador player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/Login")]
        System.Threading.Tasks.Task LoginAsync(CheckersCliente.MainService.Jugador player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/SavePlayer")]
        void SavePlayer(CheckersCliente.MainService.Jugador player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/SavePlayer")]
        System.Threading.Tasks.Task SavePlayerAsync(CheckersCliente.MainService.Jugador player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/VerifyPlayer")]
        void VerifyPlayer(CheckersCliente.MainService.Jugador player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/VerifyPlayer")]
        System.Threading.Tasks.Task VerifyPlayerAsync(CheckersCliente.MainService.Jugador player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/SendMail")]
        void SendMail(CheckersCliente.MainService.Jugador player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/SendMail")]
        System.Threading.Tasks.Task SendMailAsync(CheckersCliente.MainService.Jugador player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/PasswordForgotMail")]
        void PasswordForgotMail(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/PasswordForgotMail")]
        System.Threading.Tasks.Task PasswordForgotMailAsync(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/VerifyPin")]
        void VerifyPin(string nickname, string pin);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/VerifyPin")]
        System.Threading.Tasks.Task VerifyPinAsync(string nickname, string pin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayerManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/GetLoginResult")]
        void GetLoginResult(CheckersCliente.MainService.LoginResult resultadoLogin, CheckersCliente.MainService.Jugador player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/GetSaveResult")]
        void GetSaveResult(CheckersCliente.MainService.SaveResult resultadoGuardado, CheckersCliente.MainService.Jugador player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/GetVerifyResult")]
        void GetVerifyResult(CheckersCliente.MainService.VerificationResult resultadoVerificacion);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/GetMailResult")]
        void GetMailResult(CheckersCliente.MainService.MailResult resultadoCorreo, string actualNickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/GetPinResult")]
        void GetPinResult(CheckersCliente.MainService.PinResult verifiedPinResult, string playerNickname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayerManagerChannel : CheckersCliente.MainService.IPlayerManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayerManagerClient : System.ServiceModel.DuplexClientBase<CheckersCliente.MainService.IPlayerManager>, CheckersCliente.MainService.IPlayerManager {
        
        public PlayerManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public PlayerManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public PlayerManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Login(CheckersCliente.MainService.Jugador player) {
            base.Channel.Login(player);
        }
        
        public System.Threading.Tasks.Task LoginAsync(CheckersCliente.MainService.Jugador player) {
            return base.Channel.LoginAsync(player);
        }
        
        public void SavePlayer(CheckersCliente.MainService.Jugador player) {
            base.Channel.SavePlayer(player);
        }
        
        public System.Threading.Tasks.Task SavePlayerAsync(CheckersCliente.MainService.Jugador player) {
            return base.Channel.SavePlayerAsync(player);
        }
        
        public void VerifyPlayer(CheckersCliente.MainService.Jugador player) {
            base.Channel.VerifyPlayer(player);
        }
        
        public System.Threading.Tasks.Task VerifyPlayerAsync(CheckersCliente.MainService.Jugador player) {
            return base.Channel.VerifyPlayerAsync(player);
        }
        
        public void SendMail(CheckersCliente.MainService.Jugador player) {
            base.Channel.SendMail(player);
        }
        
        public System.Threading.Tasks.Task SendMailAsync(CheckersCliente.MainService.Jugador player) {
            return base.Channel.SendMailAsync(player);
        }
        
        public void PasswordForgotMail(string nickname) {
            base.Channel.PasswordForgotMail(nickname);
        }
        
        public System.Threading.Tasks.Task PasswordForgotMailAsync(string nickname) {
            return base.Channel.PasswordForgotMailAsync(nickname);
        }
        
        public void VerifyPin(string nickname, string pin) {
            base.Channel.VerifyPin(nickname, pin);
        }
        
        public System.Threading.Tasks.Task VerifyPinAsync(string nickname, string pin) {
            return base.Channel.VerifyPinAsync(nickname, pin);
        }
    }
}
