//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckersCliente.MainService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
    [System.SerializableAttribute()]
    public partial class Jugador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCreadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdLenguajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinConfirmacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreguntaRecuperacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RespuestaConfirmacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apodo {
            get {
                return this.ApodoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApodoField, value) != true)) {
                    this.ApodoField = value;
                    this.RaisePropertyChanged("Apodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCreador {
            get {
                return this.IdCreadorField;
            }
            set {
                if ((this.IdCreadorField.Equals(value) != true)) {
                    this.IdCreadorField = value;
                    this.RaisePropertyChanged("IdCreador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJugador {
            get {
                return this.IdJugadorField;
            }
            set {
                if ((this.IdJugadorField.Equals(value) != true)) {
                    this.IdJugadorField = value;
                    this.RaisePropertyChanged("IdJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLenguaje {
            get {
                return this.IdLenguajeField;
            }
            set {
                if ((this.IdLenguajeField.Equals(value) != true)) {
                    this.IdLenguajeField = value;
                    this.RaisePropertyChanged("IdLenguaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PinConfirmacion {
            get {
                return this.PinConfirmacionField;
            }
            set {
                if ((object.ReferenceEquals(this.PinConfirmacionField, value) != true)) {
                    this.PinConfirmacionField = value;
                    this.RaisePropertyChanged("PinConfirmacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreguntaRecuperacion {
            get {
                return this.PreguntaRecuperacionField;
            }
            set {
                if ((object.ReferenceEquals(this.PreguntaRecuperacionField, value) != true)) {
                    this.PreguntaRecuperacionField = value;
                    this.RaisePropertyChanged("PreguntaRecuperacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RespuestaConfirmacion {
            get {
                return this.RespuestaConfirmacionField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaConfirmacionField, value) != true)) {
                    this.RespuestaConfirmacionField = value;
                    this.RaisePropertyChanged("RespuestaConfirmacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResult", Namespace="http://schemas.datacontract.org/2004/07/Contratos")]
    public enum LoginResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordIncorrecto = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoExisteJugador = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExisteJugadorVerificado = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExisteJugadorNoVerificado = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveResult", Namespace="http://schemas.datacontract.org/2004/07/Contratos")]
    public enum SaveResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JugadorGuardado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NicknameExistente = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CorreoExistente = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorGuardado = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerificationResult", Namespace="http://schemas.datacontract.org/2004/07/Contratos")]
    public enum VerificationResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PinIncorrecto = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoExisteJugador = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificacionExistosa = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailResult", Namespace="http://schemas.datacontract.org/2004/07/Contratos")]
    public enum MailResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MailSend = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SendError = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownPlayer = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PinResult", Namespace="http://schemas.datacontract.org/2004/07/Contratos")]
    public enum PinResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerifiedPin = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownPin = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RankingResult", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
    public enum RankingResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NO_RANKING = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RANKING_EXISTS = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ranking", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
    [System.SerializableAttribute()]
    public partial class Ranking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDuenioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRankingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroPerdidasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroVictoriasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PartidasJugadasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RankField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistracion {
            get {
                return this.FechaRegistracionField;
            }
            set {
                if ((this.FechaRegistracionField.Equals(value) != true)) {
                    this.FechaRegistracionField = value;
                    this.RaisePropertyChanged("FechaRegistracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDuenio {
            get {
                return this.IdDuenioField;
            }
            set {
                if ((this.IdDuenioField.Equals(value) != true)) {
                    this.IdDuenioField = value;
                    this.RaisePropertyChanged("IdDuenio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRanking {
            get {
                return this.IdRankingField;
            }
            set {
                if ((this.IdRankingField.Equals(value) != true)) {
                    this.IdRankingField = value;
                    this.RaisePropertyChanged("IdRanking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroPerdidas {
            get {
                return this.NumeroPerdidasField;
            }
            set {
                if ((this.NumeroPerdidasField.Equals(value) != true)) {
                    this.NumeroPerdidasField = value;
                    this.RaisePropertyChanged("NumeroPerdidas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroVictorias {
            get {
                return this.NumeroVictoriasField;
            }
            set {
                if ((this.NumeroVictoriasField.Equals(value) != true)) {
                    this.NumeroVictoriasField = value;
                    this.RaisePropertyChanged("NumeroVictorias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PartidasJugadas {
            get {
                return this.PartidasJugadasField;
            }
            set {
                if ((this.PartidasJugadasField.Equals(value) != true)) {
                    this.PartidasJugadasField = value;
                    this.RaisePropertyChanged("PartidasJugadas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rank {
            get {
                return this.RankField;
            }
            set {
                if ((this.RankField.Equals(value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Match", Namespace="http://schemas.datacontract.org/2004/07/Contratos")]
    [System.SerializableAttribute()]
    public partial class Match : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string matchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<object, CheckersCliente.MainService.Jugador> matchPairField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matchID {
            get {
                return this.matchIDField;
            }
            set {
                if ((object.ReferenceEquals(this.matchIDField, value) != true)) {
                    this.matchIDField = value;
                    this.RaisePropertyChanged("matchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<object, CheckersCliente.MainService.Jugador> matchPair {
            get {
                return this.matchPairField;
            }
            set {
                if ((object.ReferenceEquals(this.matchPairField, value) != true)) {
                    this.matchPairField = value;
                    this.RaisePropertyChanged("matchPair");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchmakingResult", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
    public enum MatchmakingResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MATCH_FOUND = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MATCH_NOT_FOUND = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNABLE_TO_ENTER_MATCH = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MainService.IPlayerManager", CallbackContract=typeof(CheckersCliente.MainService.IPlayerManagerCallback))]
    public interface IPlayerManager {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/Login")]
        void Login(CheckersCliente.MainService.Jugador player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/Login")]
        System.Threading.Tasks.Task LoginAsync(CheckersCliente.MainService.Jugador player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/SavePlayer")]
        void SavePlayer(CheckersCliente.MainService.Jugador player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/SavePlayer")]
        System.Threading.Tasks.Task SavePlayerAsync(CheckersCliente.MainService.Jugador player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/VerifyPlayer")]
        void VerifyPlayer(CheckersCliente.MainService.Jugador player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/VerifyPlayer")]
        System.Threading.Tasks.Task VerifyPlayerAsync(CheckersCliente.MainService.Jugador player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/SendMail")]
        void SendMail(CheckersCliente.MainService.Jugador player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/SendMail")]
        System.Threading.Tasks.Task SendMailAsync(CheckersCliente.MainService.Jugador player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/PasswordForgotMail")]
        void PasswordForgotMail(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/PasswordForgotMail")]
        System.Threading.Tasks.Task PasswordForgotMailAsync(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/VerifyPin")]
        void VerifyPin(string nickname, string pin);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/VerifyPin")]
        System.Threading.Tasks.Task VerifyPinAsync(string nickname, string pin);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/ChangePassword")]
        void ChangePassword(string nickname, string pin);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/ChangePassword")]
        System.Threading.Tasks.Task ChangePasswordAsync(string nickname, string pin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayerManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/GetLoginResult")]
        void GetLoginResult(CheckersCliente.MainService.LoginResult resultadoLogin, CheckersCliente.MainService.Jugador player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/GetSaveResult")]
        void GetSaveResult(CheckersCliente.MainService.SaveResult resultadoGuardado, CheckersCliente.MainService.Jugador player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/GetVerifyResult")]
        void GetVerifyResult(CheckersCliente.MainService.VerificationResult resultadoVerificacion);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/GetMailResult")]
        void GetMailResult(CheckersCliente.MainService.MailResult resultadoCorreo, string actualNickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/GetPinResult")]
        void GetPinResult(CheckersCliente.MainService.PinResult verifiedPinResult, string playerNickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerManager/GetPasswordChangeResult")]
        void GetPasswordChangeResult(CheckersCliente.MainService.PinResult verifiedPinResult);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayerManagerChannel : CheckersCliente.MainService.IPlayerManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayerManagerClient : System.ServiceModel.DuplexClientBase<CheckersCliente.MainService.IPlayerManager>, CheckersCliente.MainService.IPlayerManager {
        
        public PlayerManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public PlayerManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public PlayerManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Login(CheckersCliente.MainService.Jugador player) {
            base.Channel.Login(player);
        }
        
        public System.Threading.Tasks.Task LoginAsync(CheckersCliente.MainService.Jugador player) {
            return base.Channel.LoginAsync(player);
        }
        
        public void SavePlayer(CheckersCliente.MainService.Jugador player) {
            base.Channel.SavePlayer(player);
        }
        
        public System.Threading.Tasks.Task SavePlayerAsync(CheckersCliente.MainService.Jugador player) {
            return base.Channel.SavePlayerAsync(player);
        }
        
        public void VerifyPlayer(CheckersCliente.MainService.Jugador player) {
            base.Channel.VerifyPlayer(player);
        }
        
        public System.Threading.Tasks.Task VerifyPlayerAsync(CheckersCliente.MainService.Jugador player) {
            return base.Channel.VerifyPlayerAsync(player);
        }
        
        public void SendMail(CheckersCliente.MainService.Jugador player) {
            base.Channel.SendMail(player);
        }
        
        public System.Threading.Tasks.Task SendMailAsync(CheckersCliente.MainService.Jugador player) {
            return base.Channel.SendMailAsync(player);
        }
        
        public void PasswordForgotMail(string nickname) {
            base.Channel.PasswordForgotMail(nickname);
        }
        
        public System.Threading.Tasks.Task PasswordForgotMailAsync(string nickname) {
            return base.Channel.PasswordForgotMailAsync(nickname);
        }
        
        public void VerifyPin(string nickname, string pin) {
            base.Channel.VerifyPin(nickname, pin);
        }
        
        public System.Threading.Tasks.Task VerifyPinAsync(string nickname, string pin) {
            return base.Channel.VerifyPinAsync(nickname, pin);
        }
        
        public void ChangePassword(string nickname, string pin) {
            base.Channel.ChangePassword(nickname, pin);
        }
        
        public System.Threading.Tasks.Task ChangePasswordAsync(string nickname, string pin) {
            return base.Channel.ChangePasswordAsync(nickname, pin);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MainService.IRankingManager", CallbackContract=typeof(CheckersCliente.MainService.IRankingManagerCallback))]
    public interface IRankingManager {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRankingManager/GetRankingData")]
        void GetRankingData();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRankingManager/GetRankingData")]
        System.Threading.Tasks.Task GetRankingDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRankingManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRankingManager/GetRankingResult")]
        void GetRankingResult(CheckersCliente.MainService.RankingResult resultado);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRankingManager/ReceiveRankingData")]
        void ReceiveRankingData(CheckersCliente.MainService.Ranking[] rankingList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRankingManagerChannel : CheckersCliente.MainService.IRankingManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RankingManagerClient : System.ServiceModel.DuplexClientBase<CheckersCliente.MainService.IRankingManager>, CheckersCliente.MainService.IRankingManager {
        
        public RankingManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public RankingManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public RankingManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RankingManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RankingManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void GetRankingData() {
            base.Channel.GetRankingData();
        }
        
        public System.Threading.Tasks.Task GetRankingDataAsync() {
            return base.Channel.GetRankingDataAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MainService.IChatManager", CallbackContract=typeof(CheckersCliente.MainService.IChatManagerCallback))]
    public interface IChatManager {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatManager/SendText")]
        void SendText(string destination, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatManager/SendText")]
        System.Threading.Tasks.Task SendTextAsync(string destination, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatManager/GetChatCallback")]
        void GetChatCallback();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatManager/GetChatCallback")]
        System.Threading.Tasks.Task GetChatCallbackAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatManager/ReceiveText")]
        void ReceiveText(string source, string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatManagerChannel : CheckersCliente.MainService.IChatManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatManagerClient : System.ServiceModel.DuplexClientBase<CheckersCliente.MainService.IChatManager>, CheckersCliente.MainService.IChatManager {
        
        public ChatManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ChatManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ChatManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SendText(string destination, string message) {
            base.Channel.SendText(destination, message);
        }
        
        public System.Threading.Tasks.Task SendTextAsync(string destination, string message) {
            return base.Channel.SendTextAsync(destination, message);
        }
        
        public void GetChatCallback() {
            base.Channel.GetChatCallback();
        }
        
        public System.Threading.Tasks.Task GetChatCallbackAsync() {
            return base.Channel.GetChatCallbackAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MainService.IMatchmakingManager", CallbackContract=typeof(CheckersCliente.MainService.IMatchmakingManagerCallback))]
    public interface IMatchmakingManager {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/HostMatch")]
        void HostMatch(CheckersCliente.MainService.Jugador currentPlayer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/HostMatch")]
        System.Threading.Tasks.Task HostMatchAsync(CheckersCliente.MainService.Jugador currentPlayer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/EnterMatch")]
        void EnterMatch(CheckersCliente.MainService.Match gameMatch, CheckersCliente.MainService.Jugador currentPlayer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/EnterMatch")]
        System.Threading.Tasks.Task EnterMatchAsync(CheckersCliente.MainService.Match gameMatch, CheckersCliente.MainService.Jugador currentPlayer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/LeaveMatch")]
        void LeaveMatch(CheckersCliente.MainService.Match gameMatch, CheckersCliente.MainService.Jugador currentPlayer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/LeaveMatch")]
        System.Threading.Tasks.Task LeaveMatchAsync(CheckersCliente.MainService.Match gameMatch, CheckersCliente.MainService.Jugador currentPlayer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchmakingManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/GetMatchmakingResult")]
        void GetMatchmakingResult(CheckersCliente.MainService.MatchmakingResult result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/GetUsersOnline")]
        void GetUsersOnline(string[] connectedUsers);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/NotifyMatchReady")]
        void NotifyMatchReady(CheckersCliente.MainService.MatchmakingResult result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/AddPlayerToMatch")]
        void AddPlayerToMatch(CheckersCliente.MainService.Jugador player);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchmakingManagerChannel : CheckersCliente.MainService.IMatchmakingManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchmakingManagerClient : System.ServiceModel.DuplexClientBase<CheckersCliente.MainService.IMatchmakingManager>, CheckersCliente.MainService.IMatchmakingManager {
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void HostMatch(CheckersCliente.MainService.Jugador currentPlayer) {
            base.Channel.HostMatch(currentPlayer);
        }
        
        public System.Threading.Tasks.Task HostMatchAsync(CheckersCliente.MainService.Jugador currentPlayer) {
            return base.Channel.HostMatchAsync(currentPlayer);
        }
        
        public void EnterMatch(CheckersCliente.MainService.Match gameMatch, CheckersCliente.MainService.Jugador currentPlayer) {
            base.Channel.EnterMatch(gameMatch, currentPlayer);
        }
        
        public System.Threading.Tasks.Task EnterMatchAsync(CheckersCliente.MainService.Match gameMatch, CheckersCliente.MainService.Jugador currentPlayer) {
            return base.Channel.EnterMatchAsync(gameMatch, currentPlayer);
        }
        
        public void LeaveMatch(CheckersCliente.MainService.Match gameMatch, CheckersCliente.MainService.Jugador currentPlayer) {
            base.Channel.LeaveMatch(gameMatch, currentPlayer);
        }
        
        public System.Threading.Tasks.Task LeaveMatchAsync(CheckersCliente.MainService.Match gameMatch, CheckersCliente.MainService.Jugador currentPlayer) {
            return base.Channel.LeaveMatchAsync(gameMatch, currentPlayer);
        }
    }
}
